### ISSUE TITLE
[RoboRIO] NI potentially dropping Hardknott support for the RoboRIO 

### ISSUE THREAD

**Issue by RyanHir** [wpilibsuite/opensdk#11]
First mentioned in the comments of #9 by @marshallmassengill.

It appears that NI is removing ARM elements in their yocto layer, this could mean many things but right now this is assuming Sumo will be the primary OS for a long while.

Tracking...
* ni/meta-nilrt#300
* ni/meta-nilrt#307
* ni/meta-nilrt#310

**Comment by RyanHir** [comment]
https://github.com/ni/meta-nilrt/pull/300/commits/8c948cce455688331218c0cddc9e69288d3b30e3

Quoted from commit message
```
The hardknott mainline doesn't currently support ARM architectures.

Remove the ARM-only packages from the base and restoremode
packagegroups, for cleanliness.

Signed-off-by: Alex Stewart <alex.stewart@ni.com>
```

**Comment by RyanHir** [comment]
Tracking issue with NI at https://github.com/ni/nilrt/issues/114

**Comment by RyanHir** [comment]
This issue is being mitigated with `roborio-staging` which will later become `roborio`. `roborio-sumo` will still be supported for if a ABI compatible toolchain is required for the RoboRIO.

The current plan is to rebuild the target runtime libraries that are provided with GCC and copy them to the RoboRIO during software deployment. Then the RoboRIO will use these libraries by updating the `LD_LIBRARY_PATH` environment variable to the custom build for robot code, preserving system libraries.

**Comment by PeterJohnson** [comment]
A custom build of Sumo is the plan going forward with newer GCC target libraries pre-installed on the Rio, so it won't be necessary to install a custom libstdc++ to use GCC 12.1.
