### ISSUE TITLE
Add X11 to bullseye builds

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/opensdk#33]
We need x11 for the pi builds to do some fun things, so it'd be nice to have those in the toolchain directly.

**Comment by RyanHir** [comment]
@ThadHouse I imagine all we need is `xorg-dev` (https://www.glfw.org/docs/latest/compile.html#compile_deps_x11). Is there anything particular you are wanting included?

**Comment by ThadHouse** [comment]
Yeah that should be fine. Just enough to we can compile glfw and then the desktop tools for raspbery pi. We'd want it in both the 32 and 64 bit toolchains. Rio is not important though, since it can never have a gui.
