### ISSUE TITLE
Toolchains need to be built on Ubuntu 20.04 to support Compiler Explorer

### ISSUE THREAD

**Issue by RyanHir** [wpilibsuite/opensdk#52]
https://github.com/compiler-explorer/compiler-explorer/pull/4568

**Comment by RyanHir** [comment]
To fix this, we need https://github.com/wpilibsuite/docker-images/pull/22 to be merged and published

**Comment by marshallmassengill** [comment]
Does this mean 20.04 can be added back to Tier 2 or Tier 3 supported architectures?  It would be really nice if it were.

**Comment by RyanHir** [comment]
Yes, the documentation is out of date but 20.04 should be considered supported.

**Comment by marshallmassengill** [comment]
> Yes, the documentation is out of date but 20.04 should be considered supported.


![](https://media.tenor.com/OdIHNAXG3hIAAAAC/star-wars-c3po.gif)

**Comment by PeterJohnson** [comment]
Tier 2 hasn't changed--I'm actually not sure why we call out Ubuntu there though; those are built with two stages (we first build a cross-compiler to that target, and then build a cross-compiler to Rio using that cross-compiler as the host compiler).  Those should instead list Debian/Raspberry Pi OS 11 as the "Known to work on".
